services:
  mysql:
    image: mysql:8.3
    networks:
      - laravel-network
    env_file:
      - path: ./mysql.env
    volumes:
      - mysql_data:/mysql_data
  laravel:
    image: bitnami/laravel:latest
    ports:
      - 8000:8000
    networks:
        - laravel-network
    env_file:
      - path: ./laravel.env
    volumes:
      - type: bind
        source: ./app
        target: /app

volumes:
  mysql_data:

networks:
  laravel-network: {}
